name: test-ci

on: [push, pull_request]

jobs:  
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master

      - name: Copy repository to cloud
        uses: appleboy/scp-action@master
        with:
          timeout: "90s"
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "./"
          target: "~/"